version: "3"
networks:
    vteam2:
        driver: bridge
services:
    server:
        image: agnesrodhe/vteam-backend:1.0
        container_name: "server"
        networks:
            vteam2:
        ports:
            - "3002:3002"
        volumes:
            - "./.env/.:/backend-api/.env"
        restart:
            "always"
    webclient:
        image: annabeerg/docker-reactjs:3.0
        container_name: "web-client"
        networks:
            vteam2:
        ports:
            - "3000:3000"
        restart:
            "always"
    app:
        image: vince232/ebikes-mobile-app:latest
        container_name: "mobile-app"
        networks:
            vteam2:
        ports:
            - "3001:3000"
        volumes:
            - "./.env/.:/home/.env"
        restart:
            "always"
