version: "3"
networks:
    viai20:
        driver: bridge
services:
    app:
        image: vince232/ebikes-mobile-app:latest
        container_name: "mobile-app"
        networks:
            viai20:
        restart:
            "always"
    webclient:
        image: annabeerg/docker-reactjs:3.0
        container_name: "webclient"
        networks:
            viai20:
        ports:
            - "3000:3000"
        restart:
            "always"